### ISSUE TITLE
same thing but for wikipedia archives

### ISSUE THREAD

**Issue by jklmm6xw** [gambolputty/german-nouns#9]
hello i need to search words with some precise syllables for my game but wiktionary is kind of empty compared to wikipedia, is there any way to make this but for wikipedia archives?

**Comment by gambolputty** [comment]
Wiktionary is a dictionary that holds information about words, like syllables of a word, pronunciation etc., whereas Wikipedia does not.
Sure, there are ways to parse Wikipedia archives. But you should look for a solution somewhere else because I'm unable to provide help for custom software. Your GitHub issue is not an issue with this python package, which is why I'm closing it now.
